apiVersion: v1
kind: Secret
metadata:
  name: weechat-config
stringData:
  relay.conf: |
    #
    # weechat -- relay.conf
    #
    
    [look]
    auto_open_buffer = on
    raw_messages = 256
    
    [network]
    allow_empty_password = off
    allowed_ips = ""
    bind_address = ""
    clients_purge_delay = 0
    compression_level = 6
    ipv6 = on
    max_clients = 5
    password = "<SUP@@h$3cRe7>"
    ssl_cert_key = "%h/ssl/relay.pem"
    ssl_priorities = "NORMAL:-VERS-SSL3.0"
    websocket_allowed_origins = ""
    
    [irc]
    backlog_max_minutes = 1440
    backlog_max_number = 256
    backlog_since_last_disconnect = on
    backlog_since_last_message = off
    backlog_tags = "irc_privmsg"
    backlog_time_format = "[%H:%M] "
    
    [port]
    weechat = 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weechat
  labels:
    app: weechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weechat
  template:
    metadata:
      labels:
        app: weechat
    spec:
      initContainers:
        - name: copy-config
          image: busybox:latest
          args:
            - cp
            - -f
            - /tmp/relay.conf
            - /home/user/.weechat/relay.conf
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: weechat-data
              mountPath: /home/user
            - name: weechat-config
              mountPath: /tmp
        - name: chown
          image: busybox:latest
          args:
            - chown
            - -R
            - "1000:1000"
            - /home/user
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: weechat-data
              mountPath: /home/user
      containers:
        - name: weechat
          image: johnnye00/weechat
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - name: weechat-data
              mountPath: /home/user
            - name: weechat-config
              mountPath: /home/user/.weechat/relay.conf
              subPath: relay.conf
      volumes:
        - name: weechat-data
          persistentVolumeClaim:
            claimName: weechat
        - name: weechat-config
          secret:
            secretName: weechat-config
            items:
              - key: relay.conf
                path: relay.conf
      
---
apiVersion: v1
kind: Service
metadata:
  name: weechat
spec:
  type: ClusterIP
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: weechat
